### ISSUE TITLE
Include datafusion in the benchmark

### ISSUE THREAD

**Issue by kszlim** [duckdblabs/db-benchmark#5]
Datafusion is another stateless query engine/dataframe library I'd be interested in seeing results for.

https://github.com/apache/arrow-datafusion

**Comment by MrPowers** [comment]
Looks like almost all of this work is done already: https://github.com/apache/arrow-datafusion/tree/main/benchmarks/db-benchmark

Would you like to add the PR @kszlim or would you like me to take a stab?

**Comment by Tmonster** [comment]
@MrPowers Was just looking at this again. Looks like the db benchmark for data fusion is here now? 
https://github.com/apache/arrow-datafusion-python/tree/main/benchmarks/db-benchmark
Would you still like to open a PR? Some of the files have benchmark initialization setup, so that would need to be trimmed, but I don't think it would be much work

**Comment by hkpeaks** [comment]
I feel interest to include datafusion in coming benchmarking https://github.com/duckdblabs/db-benchmark/issues/13#issuecomment-1578079219, is it support streaming (data large than memory scenario)?

**Comment by Dandandan** [comment]
Closed by #18
